services:
  - type: web
    name: polyworld-api
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r big_backend/backend/requirements.txt"
    startCommand: "cd big_backend && uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: POLYWORLD_CORS_ORIGINS
        value: https://jesuschrist-ruddy.vercel.app
      - key: PYTHON_VERSION
        value: 3.11.0
